graph TD
    User([Usuário]) -->|POST /submissions| APIGateway[API Gateway]
    APIGateway -->|Invocação| LambdaAPI[Lambda: API]
    LambdaAPI -->|Salva Texto| S3[(S3: Bucket de Origem)]
    LambdaAPI -->|Registra PENDING| DB[(Postgres: RDS)]
    LambdaAPI -->|Publica Job| SQS[SQS: Fila de Correção]
    SQS -->|Trigger| LambdaWorker[Lambda: Worker]
    LambdaWorker -->|Lê Texto| S3
    LambdaWorker -->|Processa e Atualiza| DB
    
    subgraph Observabilidade
        CloudWatch[CloudWatch Logs]
        XRay[AWS X-Ray]
        DLQ[SQS DLQ: Falhas]
    end
