services:
  postgres:
    extends:
      file: packages/infra/compose.db.yml
      service: postgres

  localstack:
    extends:
      file: packages/infra/compose.sls.yml
      service: localstack
    volumes:
      - ./packages/infra/init-localstack.sh:/etc/localstack/init/ready.d/init.sh:ro

  api:
    extends:
      file: apps/api/compose.yml
      service: api
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy

  worker:
    extends:
      file: apps/worker/compose.yml
      service: worker
    depends_on:
      postgres:
        condition: service_healthy
      localstack:
        condition: service_healthy

  frontend:
    extends:
      file: apps/frontend/compose.yml
      service: frontend
    depends_on:
      api:
        condition: service_healthy

volumes:
  pg_data:
  ls_data:
